apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: midas
build:
  artifacts:
    - image: frontend
      context: frontend
      docker: {}
    - image: historical-service
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: historical_service
    - image: historical-fetch-worker
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: historical_fetch_worker
    - image: historical-date-split-worker
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: historical_date_split_worker
    - image: symbol-service
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: symbol_service
    - image: trade-observer-worker
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: trade_observer_worker
    - image: notify-worker
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: notify_worker
    - image: trade-observer-service
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: trade_observer_service
    - image: trade-observer-control-worker
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: trade_observer_control_worker
    - image: token-service
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: token_service
    - image: keychain-service
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: keychain_service
    - image: transpiler-service
      context: backend
      docker:
        dockerfile: nodejs.dockerfile
        buildArgs:
          CODE_PATH: services/transpiler
    - image: bot-service
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: bot_service
manifests:
  kustomize:
    paths:
      - ./k8s
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command: [./gen.sh]
            os: [darwin, linux]
            dir: ./k8s/tls
        - host:
            command: [./mongod.sh]
            os: [darwin, linux]
            dir: ./k8s/database
        - host:
            command: [./helm_dep.sh]
            os: [darwin, linux]
            dir: ./k8s
