// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TradeType int32

const (
	TradeType_Buy  TradeType = 0
	TradeType_Sell TradeType = 1
)

var TradeType_name = map[int32]string{
	0: "Buy",
	1: "Sell",
}

var TradeType_value = map[string]int32{
	"Buy":  0,
	"Sell": 1,
}

func (x TradeType) String() string {
	return proto.EnumName(TradeType_name, int32(x))
}

func (TradeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type SubscribeRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TickInterval         string   `protobuf:"bytes,2,opt,name=tickInterval,proto3" json:"tickInterval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SubscribeRequest) GetTickInterval() string {
	if m != nil {
		return m.TickInterval
	}
	return ""
}

type SubscribeResponse struct {
	Symbol               string    `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type                 TradeType `protobuf:"varint,2,opt,name=type,proto3,enum=testbeds.TradeType" json:"type,omitempty"`
	Price                float64   `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Qty                  float64   `protobuf:"fixed64,4,opt,name=qty,proto3" json:"qty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(m, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

func (m *SubscribeResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SubscribeResponse) GetType() TradeType {
	if m != nil {
		return m.Type
	}
	return TradeType_Buy
}

func (m *SubscribeResponse) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *SubscribeResponse) GetQty() float64 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func init() {
	proto.RegisterEnum("testbeds.TradeType", TradeType_name, TradeType_value)
	proto.RegisterType((*SubscribeRequest)(nil), "testbeds.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "testbeds.SubscribeResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x75, 0x4d, 0xfa, 0x91, 0x41, 0x25, 0x8e, 0x22, 0xa1, 0x82, 0x94, 0x5c, 0x2c, 0x1e, 0x82,
	0xd4, 0x7f, 0x90, 0x83, 0xe0, 0x45, 0x30, 0xcd, 0xc9, 0x5b, 0xb3, 0x99, 0x43, 0x30, 0x36, 0xdb,
	0x9d, 0x49, 0x61, 0xc1, 0x1f, 0x2f, 0x6e, 0xb5, 0x7e, 0x60, 0x6f, 0xfb, 0xde, 0xdb, 0x79, 0xf3,
	0xe6, 0xc1, 0x31, 0x93, 0xdd, 0x34, 0x9a, 0x32, 0x63, 0x3b, 0xe9, 0x70, 0x2c, 0xc4, 0x52, 0x51,
	0xcd, 0xe9, 0x23, 0xc4, 0x8b, 0xbe, 0x62, 0x6d, 0x9b, 0x8a, 0x0a, 0x5a, 0xf7, 0xc4, 0x82, 0x17,
	0x30, 0x64, 0xf7, 0x5a, 0x75, 0x6d, 0xa2, 0xa6, 0x6a, 0x16, 0x15, 0x9f, 0x08, 0x53, 0x38, 0x92,
	0x46, 0xbf, 0x3c, 0xac, 0x84, 0xec, 0x66, 0xd9, 0x26, 0x87, 0x5e, 0xfd, 0xc5, 0xa5, 0x6f, 0x70,
	0xfa, 0xc3, 0x8f, 0x4d, 0xb7, 0x62, 0xda, 0x6b, 0x78, 0x0d, 0xa1, 0x38, 0x43, 0xde, 0xe8, 0x64,
	0x7e, 0x96, 0x7d, 0xa5, 0xca, 0x4a, 0xbb, 0xac, 0xa9, 0x74, 0x86, 0x0a, 0xff, 0x01, 0xcf, 0x61,
	0x60, 0x6c, 0xa3, 0x29, 0x09, 0xa6, 0x6a, 0xa6, 0x8a, 0x2d, 0xc0, 0x18, 0x82, 0xb5, 0xb8, 0x24,
	0xf4, 0xdc, 0xc7, 0xf3, 0xe6, 0x0a, 0xa2, 0xdd, 0x28, 0x8e, 0x20, 0xc8, 0x7b, 0x17, 0x1f, 0xe0,
	0x18, 0xc2, 0x05, 0xb5, 0x6d, 0xac, 0xe6, 0x4f, 0x30, 0x2a, 0x89, 0x25, 0xa7, 0x1a, 0xef, 0x21,
	0xda, 0x05, 0xc5, 0xc9, 0xf7, 0xea, 0xbf, 0x6d, 0x4c, 0x2e, 0xff, 0xd5, 0xb6, 0x97, 0xdd, 0xaa,
	0x7c, 0xf0, 0x1c, 0x58, 0xa3, 0xab, 0xa1, 0x2f, 0xf6, 0xee, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x1b,
	0xec, 0x84, 0x44, 0x69, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestBedClient is the client API for TestBed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestBedClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (TestBed_SubscribeClient, error)
}

type testBedClient struct {
	cc *grpc.ClientConn
}

func NewTestBedClient(cc *grpc.ClientConn) TestBedClient {
	return &testBedClient{cc}
}

func (c *testBedClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (TestBed_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TestBed_serviceDesc.Streams[0], "/testbeds.TestBed/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &testBedSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestBed_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type testBedSubscribeClient struct {
	grpc.ClientStream
}

func (x *testBedSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestBedServer is the server API for TestBed service.
type TestBedServer interface {
	Subscribe(*SubscribeRequest, TestBed_SubscribeServer) error
}

// UnimplementedTestBedServer can be embedded to have forward compatible implementations.
type UnimplementedTestBedServer struct {
}

func (*UnimplementedTestBedServer) Subscribe(req *SubscribeRequest, srv TestBed_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

func RegisterTestBedServer(s *grpc.Server, srv TestBedServer) {
	s.RegisterService(&_TestBed_serviceDesc, srv)
}

func _TestBed_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestBedServer).Subscribe(m, &testBedSubscribeServer{stream})
}

type TestBed_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type testBedSubscribeServer struct {
	grpc.ServerStream
}

func (x *testBedSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _TestBed_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testbeds.TestBed",
	HandlerType: (*TestBedServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _TestBed_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
