[package]
name = "trade_observer_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
observers = { path = "../../libs/observers" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }
subscribe = { path = "../../libs/subscribe" }

clap = { version = "4.5.8", features = ["derive"] }
tokio = { version = "1.38.0", features = [
  "signal",
  "rt",
  "rt-multi-thread",
  "macros",
] }
log = { version = "0.4", features = ["kv_unstable", "kv_unstable_serde"] }
futures = "0.3.30"
libc = "0.2.154"
mongodb = { version = "2.8.2", default-features = false, features = [
  "async-std-runtime",
] }
