// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entities.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Exchanges int32

const (
	Exchanges_Binance Exchanges = 0
)

var Exchanges_name = map[int32]string{
	0: "Binance",
}

var Exchanges_value = map[string]int32{
	"Binance": 0,
}

func (x Exchanges) String() string {
	return proto.EnumName(Exchanges_name, int32(x))
}

func (Exchanges) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{0}
}

func init() {
	proto.RegisterEnum("entities.Exchanges", Exchanges_name, Exchanges_value)
}

func init() { proto.RegisterFile("entities.proto", fileDescriptor_a5f7344b79fcc63d) }

var fileDescriptor_a5f7344b79fcc63d = []byte{
	// 82 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcd, 0x2b, 0xc9,
	0x2c, 0xc9, 0x4c, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0xb5, 0x24,
	0xb8, 0x38, 0x5d, 0x2b, 0x92, 0x33, 0x12, 0xf3, 0xd2, 0x53, 0x8b, 0x85, 0xb8, 0xb9, 0xd8, 0x9d,
	0x32, 0xf3, 0x12, 0xf3, 0x92, 0x53, 0x05, 0x18, 0x9c, 0x58, 0xa3, 0x98, 0x8b, 0x0a, 0x92, 0x93,
	0xd8, 0xc0, 0x3a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0x4f, 0x49, 0xf0, 0x43, 0x00,
	0x00, 0x00,
}
