// source: symbols.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var entities_pb = require('./entities_pb.js');
goog.object.extend(proto, entities_pb);
goog.exportSymbol('proto.symbols.BaseSymbols', null, global);
goog.exportSymbol('proto.symbols.SymbolInfo', null, global);
goog.exportSymbol('proto.symbols.SymbolList', null, global);
goog.exportSymbol('proto.symbols.Type', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.symbols.SymbolInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.symbols.SymbolInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.symbols.SymbolInfo.displayName = 'proto.symbols.SymbolInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.symbols.SymbolList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.symbols.SymbolList.repeatedFields_, null);
};
goog.inherits(proto.symbols.SymbolList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.symbols.SymbolList.displayName = 'proto.symbols.SymbolList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.symbols.BaseSymbols = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.symbols.BaseSymbols.repeatedFields_, null);
};
goog.inherits(proto.symbols.BaseSymbols, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.symbols.BaseSymbols.displayName = 'proto.symbols.BaseSymbols';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.symbols.SymbolInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.symbols.SymbolInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.symbols.SymbolInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.symbols.SymbolInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    exchange: jspb.Message.getFieldWithDefault(msg, 1, 0),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0),
    symbol: jspb.Message.getFieldWithDefault(msg, 3, ""),
    status: jspb.Message.getFieldWithDefault(msg, 4, ""),
    base: jspb.Message.getFieldWithDefault(msg, 5, ""),
    quote: jspb.Message.getFieldWithDefault(msg, 6, ""),
    basePrecision: jspb.Message.getFieldWithDefault(msg, 7, 0),
    quotePrecision: jspb.Message.getFieldWithDefault(msg, 8, 0),
    baseCommissionPrecision: jspb.Message.getFieldWithDefault(msg, 9, 0),
    quoteCommissionPrecision: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.symbols.SymbolInfo}
 */
proto.symbols.SymbolInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.symbols.SymbolInfo;
  return proto.symbols.SymbolInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.symbols.SymbolInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.symbols.SymbolInfo}
 */
proto.symbols.SymbolInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.entities.Exchanges} */ (reader.readEnum());
      msg.setExchange(value);
      break;
    case 2:
      var value = /** @type {!proto.symbols.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbol(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setBase(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuote(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBasePrecision(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setQuotePrecision(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBaseCommissionPrecision(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setQuoteCommissionPrecision(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.symbols.SymbolInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.symbols.SymbolInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.symbols.SymbolInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.symbols.SymbolInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExchange();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getBase();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getQuote();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getBasePrecision();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getQuotePrecision();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getBaseCommissionPrecision();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getQuoteCommissionPrecision();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
};


/**
 * optional entities.Exchanges exchange = 1;
 * @return {!proto.entities.Exchanges}
 */
proto.symbols.SymbolInfo.prototype.getExchange = function() {
  return /** @type {!proto.entities.Exchanges} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.entities.Exchanges} value
 * @return {!proto.symbols.SymbolInfo} returns this
 */
proto.symbols.SymbolInfo.prototype.setExchange = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Type type = 2;
 * @return {!proto.symbols.Type}
 */
proto.symbols.SymbolInfo.prototype.getType = function() {
  return /** @type {!proto.symbols.Type} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.symbols.Type} value
 * @return {!proto.symbols.SymbolInfo} returns this
 */
proto.symbols.SymbolInfo.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string symbol = 3;
 * @return {string}
 */
proto.symbols.SymbolInfo.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.symbols.SymbolInfo} returns this
 */
proto.symbols.SymbolInfo.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string status = 4;
 * @return {string}
 */
proto.symbols.SymbolInfo.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.symbols.SymbolInfo} returns this
 */
proto.symbols.SymbolInfo.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string base = 5;
 * @return {string}
 */
proto.symbols.SymbolInfo.prototype.getBase = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.symbols.SymbolInfo} returns this
 */
proto.symbols.SymbolInfo.prototype.setBase = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string quote = 6;
 * @return {string}
 */
proto.symbols.SymbolInfo.prototype.getQuote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.symbols.SymbolInfo} returns this
 */
proto.symbols.SymbolInfo.prototype.setQuote = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int64 base_precision = 7;
 * @return {number}
 */
proto.symbols.SymbolInfo.prototype.getBasePrecision = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.symbols.SymbolInfo} returns this
 */
proto.symbols.SymbolInfo.prototype.setBasePrecision = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 quote_precision = 8;
 * @return {number}
 */
proto.symbols.SymbolInfo.prototype.getQuotePrecision = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.symbols.SymbolInfo} returns this
 */
proto.symbols.SymbolInfo.prototype.setQuotePrecision = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 base_commission_precision = 9;
 * @return {number}
 */
proto.symbols.SymbolInfo.prototype.getBaseCommissionPrecision = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.symbols.SymbolInfo} returns this
 */
proto.symbols.SymbolInfo.prototype.setBaseCommissionPrecision = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int64 quote_commission_precision = 10;
 * @return {number}
 */
proto.symbols.SymbolInfo.prototype.getQuoteCommissionPrecision = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.symbols.SymbolInfo} returns this
 */
proto.symbols.SymbolInfo.prototype.setQuoteCommissionPrecision = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.symbols.SymbolList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.symbols.SymbolList.prototype.toObject = function(opt_includeInstance) {
  return proto.symbols.SymbolList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.symbols.SymbolList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.symbols.SymbolList.toObject = function(includeInstance, msg) {
  var f, obj = {
    symbolsList: jspb.Message.toObjectList(msg.getSymbolsList(),
    proto.symbols.SymbolInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.symbols.SymbolList}
 */
proto.symbols.SymbolList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.symbols.SymbolList;
  return proto.symbols.SymbolList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.symbols.SymbolList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.symbols.SymbolList}
 */
proto.symbols.SymbolList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.symbols.SymbolInfo;
      reader.readMessage(value,proto.symbols.SymbolInfo.deserializeBinaryFromReader);
      msg.addSymbols(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.symbols.SymbolList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.symbols.SymbolList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.symbols.SymbolList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.symbols.SymbolList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSymbolsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.symbols.SymbolInfo.serializeBinaryToWriter
    );
  }
};


/**
 * repeated SymbolInfo symbols = 1;
 * @return {!Array<!proto.symbols.SymbolInfo>}
 */
proto.symbols.SymbolList.prototype.getSymbolsList = function() {
  return /** @type{!Array<!proto.symbols.SymbolInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.symbols.SymbolInfo, 1));
};


/**
 * @param {!Array<!proto.symbols.SymbolInfo>} value
 * @return {!proto.symbols.SymbolList} returns this
*/
proto.symbols.SymbolList.prototype.setSymbolsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.symbols.SymbolInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.symbols.SymbolInfo}
 */
proto.symbols.SymbolList.prototype.addSymbols = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.symbols.SymbolInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.symbols.SymbolList} returns this
 */
proto.symbols.SymbolList.prototype.clearSymbolsList = function() {
  return this.setSymbolsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.symbols.BaseSymbols.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.symbols.BaseSymbols.prototype.toObject = function(opt_includeInstance) {
  return proto.symbols.BaseSymbols.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.symbols.BaseSymbols} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.symbols.BaseSymbols.toObject = function(includeInstance, msg) {
  var f, obj = {
    symbolsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.symbols.BaseSymbols}
 */
proto.symbols.BaseSymbols.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.symbols.BaseSymbols;
  return proto.symbols.BaseSymbols.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.symbols.BaseSymbols} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.symbols.BaseSymbols}
 */
proto.symbols.BaseSymbols.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addSymbols(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.symbols.BaseSymbols.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.symbols.BaseSymbols.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.symbols.BaseSymbols} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.symbols.BaseSymbols.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSymbolsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string symbols = 1;
 * @return {!Array<string>}
 */
proto.symbols.BaseSymbols.prototype.getSymbolsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.symbols.BaseSymbols} returns this
 */
proto.symbols.BaseSymbols.prototype.setSymbolsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.symbols.BaseSymbols} returns this
 */
proto.symbols.BaseSymbols.prototype.addSymbols = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.symbols.BaseSymbols} returns this
 */
proto.symbols.BaseSymbols.prototype.clearSymbolsList = function() {
  return this.setSymbolsList([]);
};


/**
 * @enum {number}
 */
proto.symbols.Type = {
  CRYPTO: 0,
  STOCK: 1
};

goog.object.extend(exports, proto.symbols);
