[package]
name = "position_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
position = { path = "../../libs/position" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }
access_logger = { path = "../../libs/access_logger" }
csrf = { path = "../../libs/csrf" }

mongodb = { version = "2.8.2", default-features = false, features = [
  "async-std-runtime",
  "bson-chrono-0_4",
] }
tokio = { version = "1.37.0", features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "signal",
] }
warp = { version = "0.3.7", features = ["tls"] }
serde = { version = "1.0.197", features = ["derive"] }
futures = "0.3.30"
log = { version = "0.4", features = ["kv_unstable", "kv_unstable_serde"] }
