// source: bot.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.bot.Bot', null, global);
goog.exportSymbol('proto.bot.CompareOp', null, global);
goog.exportSymbol('proto.bot.ConditionItem', null, global);
goog.exportSymbol('proto.bot.Manual', null, global);
goog.exportSymbol('proto.bot.Position', null, global);
goog.exportSymbol('proto.bot.PositionStatus', null, global);
goog.exportSymbol('proto.bot.TargetIndicator', null, global);
goog.exportSymbol('proto.bot.TargetIndicator.TargetCase', null, global);
goog.exportSymbol('proto.bot.Trailing', null, global);
goog.exportSymbol('proto.bot.Trigger', null, global);
goog.exportSymbol('proto.bot.Trigger.TriggerCase', null, global);
goog.exportSymbol('proto.bot.TriggerType', null, global);
goog.exportSymbol('proto.bot.TriggerType.TypeCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bot.TargetIndicator = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.bot.TargetIndicator.oneofGroups_);
};
goog.inherits(proto.bot.TargetIndicator, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bot.TargetIndicator.displayName = 'proto.bot.TargetIndicator';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bot.ConditionItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bot.ConditionItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bot.ConditionItem.displayName = 'proto.bot.ConditionItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bot.Trigger = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.bot.Trigger.oneofGroups_);
};
goog.inherits(proto.bot.Trigger, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bot.Trigger.displayName = 'proto.bot.Trigger';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bot.Trailing = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bot.Trailing, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bot.Trailing.displayName = 'proto.bot.Trailing';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bot.Manual = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bot.Manual, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bot.Manual.displayName = 'proto.bot.Manual';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bot.TriggerType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.bot.TriggerType.oneofGroups_);
};
goog.inherits(proto.bot.TriggerType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bot.TriggerType.displayName = 'proto.bot.TriggerType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bot.Bot = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bot.Bot, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bot.Bot.displayName = 'proto.bot.Bot';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bot.Position = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bot.Position, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bot.Position.displayName = 'proto.bot.Position';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.bot.TargetIndicator.oneofGroups_ = [[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]];

/**
 * @enum {number}
 */
proto.bot.TargetIndicator.TargetCase = {
  TARGET_NOT_SET: 0,
  ABSOLUTE: 1,
  PERCENTAGE: 2,
  CURRENTPRICE: 3,
  WATCHPRICE: 4,
  CURRENTVOLUME: 5,
  VOLUMELASTTICK: 6,
  HIGHPRICELASTTICK: 7,
  LOWPRICELASTTICK: 8,
  MIDPRICELASTTICK: 9,
  OPENPRICELASTTICK: 10,
  CLOSEPRICELASTTICK: 11,
  SMA: 12,
  EMA: 13,
  RSI: 14,
  MACD: 15,
  CCI: 16
};

/**
 * @return {proto.bot.TargetIndicator.TargetCase}
 */
proto.bot.TargetIndicator.prototype.getTargetCase = function() {
  return /** @type {proto.bot.TargetIndicator.TargetCase} */(jspb.Message.computeOneofCase(this, proto.bot.TargetIndicator.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bot.TargetIndicator.prototype.toObject = function(opt_includeInstance) {
  return proto.bot.TargetIndicator.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bot.TargetIndicator} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.TargetIndicator.toObject = function(includeInstance, msg) {
  var f, obj = {
    absolute: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    percentage: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    currentprice: (f = msg.getCurrentprice()) && google_protobuf_empty_pb.Empty.toObject(includeInstance, f),
    watchprice: (f = msg.getWatchprice()) && google_protobuf_empty_pb.Empty.toObject(includeInstance, f),
    currentvolume: (f = msg.getCurrentvolume()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    volumelasttick: (f = msg.getVolumelasttick()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    highpricelasttick: (f = msg.getHighpricelasttick()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    lowpricelasttick: (f = msg.getLowpricelasttick()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    midpricelasttick: (f = msg.getMidpricelasttick()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    openpricelasttick: (f = msg.getOpenpricelasttick()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    closepricelasttick: (f = msg.getClosepricelasttick()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    sma: (f = msg.getSma()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    ema: (f = msg.getEma()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    rsi: (f = msg.getRsi()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    macd: (f = msg.getMacd()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    cci: (f = msg.getCci()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bot.TargetIndicator}
 */
proto.bot.TargetIndicator.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bot.TargetIndicator;
  return proto.bot.TargetIndicator.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bot.TargetIndicator} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bot.TargetIndicator}
 */
proto.bot.TargetIndicator.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAbsolute(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPercentage(value);
      break;
    case 3:
      var value = new google_protobuf_empty_pb.Empty;
      reader.readMessage(value,google_protobuf_empty_pb.Empty.deserializeBinaryFromReader);
      msg.setCurrentprice(value);
      break;
    case 4:
      var value = new google_protobuf_empty_pb.Empty;
      reader.readMessage(value,google_protobuf_empty_pb.Empty.deserializeBinaryFromReader);
      msg.setWatchprice(value);
      break;
    case 5:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setCurrentvolume(value);
      break;
    case 6:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setVolumelasttick(value);
      break;
    case 7:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setHighpricelasttick(value);
      break;
    case 8:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setLowpricelasttick(value);
      break;
    case 9:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setMidpricelasttick(value);
      break;
    case 10:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setOpenpricelasttick(value);
      break;
    case 11:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setClosepricelasttick(value);
      break;
    case 12:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setSma(value);
      break;
    case 13:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setEma(value);
      break;
    case 14:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setRsi(value);
      break;
    case 15:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setMacd(value);
      break;
    case 16:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setCci(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bot.TargetIndicator.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bot.TargetIndicator.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bot.TargetIndicator} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.TargetIndicator.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getCurrentprice();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_empty_pb.Empty.serializeBinaryToWriter
    );
  }
  f = message.getWatchprice();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_empty_pb.Empty.serializeBinaryToWriter
    );
  }
  f = message.getCurrentvolume();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getVolumelasttick();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getHighpricelasttick();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getLowpricelasttick();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getMidpricelasttick();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getOpenpricelasttick();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getClosepricelasttick();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getSma();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getEma();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getRsi();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getMacd();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getCci();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional double absolute = 1;
 * @return {number}
 */
proto.bot.TargetIndicator.prototype.getAbsolute = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.setAbsolute = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearAbsolute = function() {
  return jspb.Message.setOneofField(this, 1, proto.bot.TargetIndicator.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasAbsolute = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional double percentage = 2;
 * @return {number}
 */
proto.bot.TargetIndicator.prototype.getPercentage = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.setPercentage = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearPercentage = function() {
  return jspb.Message.setOneofField(this, 2, proto.bot.TargetIndicator.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasPercentage = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Empty currentPrice = 3;
 * @return {?proto.google.protobuf.Empty}
 */
proto.bot.TargetIndicator.prototype.getCurrentprice = function() {
  return /** @type{?proto.google.protobuf.Empty} */ (
    jspb.Message.getWrapperField(this, google_protobuf_empty_pb.Empty, 3));
};


/**
 * @param {?proto.google.protobuf.Empty|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setCurrentprice = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearCurrentprice = function() {
  return this.setCurrentprice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasCurrentprice = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Empty watchPrice = 4;
 * @return {?proto.google.protobuf.Empty}
 */
proto.bot.TargetIndicator.prototype.getWatchprice = function() {
  return /** @type{?proto.google.protobuf.Empty} */ (
    jspb.Message.getWrapperField(this, google_protobuf_empty_pb.Empty, 4));
};


/**
 * @param {?proto.google.protobuf.Empty|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setWatchprice = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearWatchprice = function() {
  return this.setWatchprice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasWatchprice = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Duration currentVolume = 5;
 * @return {?proto.google.protobuf.Duration}
 */
proto.bot.TargetIndicator.prototype.getCurrentvolume = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 5));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setCurrentvolume = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearCurrentvolume = function() {
  return this.setCurrentvolume(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasCurrentvolume = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Duration volumeLastTick = 6;
 * @return {?proto.google.protobuf.Duration}
 */
proto.bot.TargetIndicator.prototype.getVolumelasttick = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 6));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setVolumelasttick = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearVolumelasttick = function() {
  return this.setVolumelasttick(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasVolumelasttick = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Duration highPriceLastTick = 7;
 * @return {?proto.google.protobuf.Duration}
 */
proto.bot.TargetIndicator.prototype.getHighpricelasttick = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 7));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setHighpricelasttick = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearHighpricelasttick = function() {
  return this.setHighpricelasttick(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasHighpricelasttick = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Duration lowPriceLastTick = 8;
 * @return {?proto.google.protobuf.Duration}
 */
proto.bot.TargetIndicator.prototype.getLowpricelasttick = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 8));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setLowpricelasttick = function(value) {
  return jspb.Message.setOneofWrapperField(this, 8, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearLowpricelasttick = function() {
  return this.setLowpricelasttick(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasLowpricelasttick = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Duration midPriceLastTick = 9;
 * @return {?proto.google.protobuf.Duration}
 */
proto.bot.TargetIndicator.prototype.getMidpricelasttick = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 9));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setMidpricelasttick = function(value) {
  return jspb.Message.setOneofWrapperField(this, 9, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearMidpricelasttick = function() {
  return this.setMidpricelasttick(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasMidpricelasttick = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.Duration openPriceLastTick = 10;
 * @return {?proto.google.protobuf.Duration}
 */
proto.bot.TargetIndicator.prototype.getOpenpricelasttick = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 10));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setOpenpricelasttick = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearOpenpricelasttick = function() {
  return this.setOpenpricelasttick(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasOpenpricelasttick = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional google.protobuf.Duration closePriceLastTick = 11;
 * @return {?proto.google.protobuf.Duration}
 */
proto.bot.TargetIndicator.prototype.getClosepricelasttick = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 11));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setClosepricelasttick = function(value) {
  return jspb.Message.setOneofWrapperField(this, 11, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearClosepricelasttick = function() {
  return this.setClosepricelasttick(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasClosepricelasttick = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional google.protobuf.Duration SMA = 12;
 * @return {?proto.google.protobuf.Duration}
 */
proto.bot.TargetIndicator.prototype.getSma = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 12));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setSma = function(value) {
  return jspb.Message.setOneofWrapperField(this, 12, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearSma = function() {
  return this.setSma(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasSma = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional google.protobuf.Duration EMA = 13;
 * @return {?proto.google.protobuf.Duration}
 */
proto.bot.TargetIndicator.prototype.getEma = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 13));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setEma = function(value) {
  return jspb.Message.setOneofWrapperField(this, 13, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearEma = function() {
  return this.setEma(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasEma = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional google.protobuf.Duration RSI = 14;
 * @return {?proto.google.protobuf.Duration}
 */
proto.bot.TargetIndicator.prototype.getRsi = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 14));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setRsi = function(value) {
  return jspb.Message.setOneofWrapperField(this, 14, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearRsi = function() {
  return this.setRsi(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasRsi = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional google.protobuf.Duration MACD = 15;
 * @return {?proto.google.protobuf.Duration}
 */
proto.bot.TargetIndicator.prototype.getMacd = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 15));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setMacd = function(value) {
  return jspb.Message.setOneofWrapperField(this, 15, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearMacd = function() {
  return this.setMacd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasMacd = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional google.protobuf.Duration CCI = 16;
 * @return {?proto.google.protobuf.Duration}
 */
proto.bot.TargetIndicator.prototype.getCci = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 16));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.bot.TargetIndicator} returns this
*/
proto.bot.TargetIndicator.prototype.setCci = function(value) {
  return jspb.Message.setOneofWrapperField(this, 16, proto.bot.TargetIndicator.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TargetIndicator} returns this
 */
proto.bot.TargetIndicator.prototype.clearCci = function() {
  return this.setCci(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TargetIndicator.prototype.hasCci = function() {
  return jspb.Message.getField(this, 16) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bot.ConditionItem.prototype.toObject = function(opt_includeInstance) {
  return proto.bot.ConditionItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bot.ConditionItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.ConditionItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    cmp: jspb.Message.getFieldWithDefault(msg, 1, 0),
    opa: (f = msg.getOpa()) && proto.bot.TargetIndicator.toObject(includeInstance, f),
    opb: (f = msg.getOpb()) && proto.bot.TargetIndicator.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bot.ConditionItem}
 */
proto.bot.ConditionItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bot.ConditionItem;
  return proto.bot.ConditionItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bot.ConditionItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bot.ConditionItem}
 */
proto.bot.ConditionItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.bot.CompareOp} */ (reader.readEnum());
      msg.setCmp(value);
      break;
    case 2:
      var value = new proto.bot.TargetIndicator;
      reader.readMessage(value,proto.bot.TargetIndicator.deserializeBinaryFromReader);
      msg.setOpa(value);
      break;
    case 3:
      var value = new proto.bot.TargetIndicator;
      reader.readMessage(value,proto.bot.TargetIndicator.deserializeBinaryFromReader);
      msg.setOpb(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bot.ConditionItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bot.ConditionItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bot.ConditionItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.ConditionItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCmp();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getOpa();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.bot.TargetIndicator.serializeBinaryToWriter
    );
  }
  f = message.getOpb();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.bot.TargetIndicator.serializeBinaryToWriter
    );
  }
};


/**
 * optional CompareOp cmp = 1;
 * @return {!proto.bot.CompareOp}
 */
proto.bot.ConditionItem.prototype.getCmp = function() {
  return /** @type {!proto.bot.CompareOp} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.bot.CompareOp} value
 * @return {!proto.bot.ConditionItem} returns this
 */
proto.bot.ConditionItem.prototype.setCmp = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional TargetIndicator opA = 2;
 * @return {?proto.bot.TargetIndicator}
 */
proto.bot.ConditionItem.prototype.getOpa = function() {
  return /** @type{?proto.bot.TargetIndicator} */ (
    jspb.Message.getWrapperField(this, proto.bot.TargetIndicator, 2));
};


/**
 * @param {?proto.bot.TargetIndicator|undefined} value
 * @return {!proto.bot.ConditionItem} returns this
*/
proto.bot.ConditionItem.prototype.setOpa = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.ConditionItem} returns this
 */
proto.bot.ConditionItem.prototype.clearOpa = function() {
  return this.setOpa(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.ConditionItem.prototype.hasOpa = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional TargetIndicator opB = 3;
 * @return {?proto.bot.TargetIndicator}
 */
proto.bot.ConditionItem.prototype.getOpb = function() {
  return /** @type{?proto.bot.TargetIndicator} */ (
    jspb.Message.getWrapperField(this, proto.bot.TargetIndicator, 3));
};


/**
 * @param {?proto.bot.TargetIndicator|undefined} value
 * @return {!proto.bot.ConditionItem} returns this
*/
proto.bot.ConditionItem.prototype.setOpb = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.ConditionItem} returns this
 */
proto.bot.ConditionItem.prototype.clearOpb = function() {
  return this.setOpb(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.ConditionItem.prototype.hasOpb = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.bot.Trigger.oneofGroups_ = [[1,2,3,4]];

/**
 * @enum {number}
 */
proto.bot.Trigger.TriggerCase = {
  TRIGGER_NOT_SET: 0,
  AND: 1,
  OR: 2,
  NOT: 3,
  SINGLE: 4
};

/**
 * @return {proto.bot.Trigger.TriggerCase}
 */
proto.bot.Trigger.prototype.getTriggerCase = function() {
  return /** @type {proto.bot.Trigger.TriggerCase} */(jspb.Message.computeOneofCase(this, proto.bot.Trigger.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bot.Trigger.prototype.toObject = function(opt_includeInstance) {
  return proto.bot.Trigger.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bot.Trigger} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.Trigger.toObject = function(includeInstance, msg) {
  var f, obj = {
    and: (f = msg.getAnd()) && proto.bot.Trigger.toObject(includeInstance, f),
    or: (f = msg.getOr()) && proto.bot.Trigger.toObject(includeInstance, f),
    not: (f = msg.getNot()) && proto.bot.Trigger.toObject(includeInstance, f),
    single: (f = msg.getSingle()) && proto.bot.ConditionItem.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bot.Trigger}
 */
proto.bot.Trigger.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bot.Trigger;
  return proto.bot.Trigger.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bot.Trigger} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bot.Trigger}
 */
proto.bot.Trigger.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bot.Trigger;
      reader.readMessage(value,proto.bot.Trigger.deserializeBinaryFromReader);
      msg.setAnd(value);
      break;
    case 2:
      var value = new proto.bot.Trigger;
      reader.readMessage(value,proto.bot.Trigger.deserializeBinaryFromReader);
      msg.setOr(value);
      break;
    case 3:
      var value = new proto.bot.Trigger;
      reader.readMessage(value,proto.bot.Trigger.deserializeBinaryFromReader);
      msg.setNot(value);
      break;
    case 4:
      var value = new proto.bot.ConditionItem;
      reader.readMessage(value,proto.bot.ConditionItem.deserializeBinaryFromReader);
      msg.setSingle(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bot.Trigger.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bot.Trigger.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bot.Trigger} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.Trigger.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnd();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.bot.Trigger.serializeBinaryToWriter
    );
  }
  f = message.getOr();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.bot.Trigger.serializeBinaryToWriter
    );
  }
  f = message.getNot();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.bot.Trigger.serializeBinaryToWriter
    );
  }
  f = message.getSingle();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.bot.ConditionItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional Trigger and = 1;
 * @return {?proto.bot.Trigger}
 */
proto.bot.Trigger.prototype.getAnd = function() {
  return /** @type{?proto.bot.Trigger} */ (
    jspb.Message.getWrapperField(this, proto.bot.Trigger, 1));
};


/**
 * @param {?proto.bot.Trigger|undefined} value
 * @return {!proto.bot.Trigger} returns this
*/
proto.bot.Trigger.prototype.setAnd = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.bot.Trigger.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.Trigger} returns this
 */
proto.bot.Trigger.prototype.clearAnd = function() {
  return this.setAnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.Trigger.prototype.hasAnd = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Trigger or = 2;
 * @return {?proto.bot.Trigger}
 */
proto.bot.Trigger.prototype.getOr = function() {
  return /** @type{?proto.bot.Trigger} */ (
    jspb.Message.getWrapperField(this, proto.bot.Trigger, 2));
};


/**
 * @param {?proto.bot.Trigger|undefined} value
 * @return {!proto.bot.Trigger} returns this
*/
proto.bot.Trigger.prototype.setOr = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.bot.Trigger.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.Trigger} returns this
 */
proto.bot.Trigger.prototype.clearOr = function() {
  return this.setOr(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.Trigger.prototype.hasOr = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Trigger not = 3;
 * @return {?proto.bot.Trigger}
 */
proto.bot.Trigger.prototype.getNot = function() {
  return /** @type{?proto.bot.Trigger} */ (
    jspb.Message.getWrapperField(this, proto.bot.Trigger, 3));
};


/**
 * @param {?proto.bot.Trigger|undefined} value
 * @return {!proto.bot.Trigger} returns this
*/
proto.bot.Trigger.prototype.setNot = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.bot.Trigger.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.Trigger} returns this
 */
proto.bot.Trigger.prototype.clearNot = function() {
  return this.setNot(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.Trigger.prototype.hasNot = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ConditionItem single = 4;
 * @return {?proto.bot.ConditionItem}
 */
proto.bot.Trigger.prototype.getSingle = function() {
  return /** @type{?proto.bot.ConditionItem} */ (
    jspb.Message.getWrapperField(this, proto.bot.ConditionItem, 4));
};


/**
 * @param {?proto.bot.ConditionItem|undefined} value
 * @return {!proto.bot.Trigger} returns this
*/
proto.bot.Trigger.prototype.setSingle = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.bot.Trigger.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.Trigger} returns this
 */
proto.bot.Trigger.prototype.clearSingle = function() {
  return this.setSingle(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.Trigger.prototype.hasSingle = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bot.Trailing.prototype.toObject = function(opt_includeInstance) {
  return proto.bot.Trailing.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bot.Trailing} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.Trailing.toObject = function(includeInstance, msg) {
  var f, obj = {
    watchpoint: (f = msg.getWatchpoint()) && proto.bot.Trigger.toObject(includeInstance, f),
    unwatchpoint: (f = msg.getUnwatchpoint()) && proto.bot.Trigger.toObject(includeInstance, f),
    triggerpoint: (f = msg.getTriggerpoint()) && proto.bot.Trigger.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bot.Trailing}
 */
proto.bot.Trailing.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bot.Trailing;
  return proto.bot.Trailing.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bot.Trailing} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bot.Trailing}
 */
proto.bot.Trailing.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bot.Trigger;
      reader.readMessage(value,proto.bot.Trigger.deserializeBinaryFromReader);
      msg.setWatchpoint(value);
      break;
    case 2:
      var value = new proto.bot.Trigger;
      reader.readMessage(value,proto.bot.Trigger.deserializeBinaryFromReader);
      msg.setUnwatchpoint(value);
      break;
    case 3:
      var value = new proto.bot.Trigger;
      reader.readMessage(value,proto.bot.Trigger.deserializeBinaryFromReader);
      msg.setTriggerpoint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bot.Trailing.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bot.Trailing.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bot.Trailing} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.Trailing.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWatchpoint();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.bot.Trigger.serializeBinaryToWriter
    );
  }
  f = message.getUnwatchpoint();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.bot.Trigger.serializeBinaryToWriter
    );
  }
  f = message.getTriggerpoint();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.bot.Trigger.serializeBinaryToWriter
    );
  }
};


/**
 * optional Trigger watchPoint = 1;
 * @return {?proto.bot.Trigger}
 */
proto.bot.Trailing.prototype.getWatchpoint = function() {
  return /** @type{?proto.bot.Trigger} */ (
    jspb.Message.getWrapperField(this, proto.bot.Trigger, 1));
};


/**
 * @param {?proto.bot.Trigger|undefined} value
 * @return {!proto.bot.Trailing} returns this
*/
proto.bot.Trailing.prototype.setWatchpoint = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.Trailing} returns this
 */
proto.bot.Trailing.prototype.clearWatchpoint = function() {
  return this.setWatchpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.Trailing.prototype.hasWatchpoint = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Trigger unwatchPoint = 2;
 * @return {?proto.bot.Trigger}
 */
proto.bot.Trailing.prototype.getUnwatchpoint = function() {
  return /** @type{?proto.bot.Trigger} */ (
    jspb.Message.getWrapperField(this, proto.bot.Trigger, 2));
};


/**
 * @param {?proto.bot.Trigger|undefined} value
 * @return {!proto.bot.Trailing} returns this
*/
proto.bot.Trailing.prototype.setUnwatchpoint = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.Trailing} returns this
 */
proto.bot.Trailing.prototype.clearUnwatchpoint = function() {
  return this.setUnwatchpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.Trailing.prototype.hasUnwatchpoint = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Trigger triggerPoint = 3;
 * @return {?proto.bot.Trigger}
 */
proto.bot.Trailing.prototype.getTriggerpoint = function() {
  return /** @type{?proto.bot.Trigger} */ (
    jspb.Message.getWrapperField(this, proto.bot.Trigger, 3));
};


/**
 * @param {?proto.bot.Trigger|undefined} value
 * @return {!proto.bot.Trailing} returns this
*/
proto.bot.Trailing.prototype.setTriggerpoint = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.Trailing} returns this
 */
proto.bot.Trailing.prototype.clearTriggerpoint = function() {
  return this.setTriggerpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.Trailing.prototype.hasTriggerpoint = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bot.Manual.prototype.toObject = function(opt_includeInstance) {
  return proto.bot.Manual.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bot.Manual} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.Manual.toObject = function(includeInstance, msg) {
  var f, obj = {
    entrypoint: (f = msg.getEntrypoint()) && proto.bot.Trailing.toObject(includeInstance, f),
    exitpoint: (f = msg.getExitpoint()) && proto.bot.Trailing.toObject(includeInstance, f),
    losscutpoint: (f = msg.getLosscutpoint()) && proto.bot.Trigger.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bot.Manual}
 */
proto.bot.Manual.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bot.Manual;
  return proto.bot.Manual.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bot.Manual} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bot.Manual}
 */
proto.bot.Manual.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bot.Trailing;
      reader.readMessage(value,proto.bot.Trailing.deserializeBinaryFromReader);
      msg.setEntrypoint(value);
      break;
    case 2:
      var value = new proto.bot.Trailing;
      reader.readMessage(value,proto.bot.Trailing.deserializeBinaryFromReader);
      msg.setExitpoint(value);
      break;
    case 3:
      var value = new proto.bot.Trigger;
      reader.readMessage(value,proto.bot.Trigger.deserializeBinaryFromReader);
      msg.setLosscutpoint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bot.Manual.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bot.Manual.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bot.Manual} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.Manual.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntrypoint();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.bot.Trailing.serializeBinaryToWriter
    );
  }
  f = message.getExitpoint();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.bot.Trailing.serializeBinaryToWriter
    );
  }
  f = message.getLosscutpoint();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.bot.Trigger.serializeBinaryToWriter
    );
  }
};


/**
 * optional Trailing entryPoint = 1;
 * @return {?proto.bot.Trailing}
 */
proto.bot.Manual.prototype.getEntrypoint = function() {
  return /** @type{?proto.bot.Trailing} */ (
    jspb.Message.getWrapperField(this, proto.bot.Trailing, 1));
};


/**
 * @param {?proto.bot.Trailing|undefined} value
 * @return {!proto.bot.Manual} returns this
*/
proto.bot.Manual.prototype.setEntrypoint = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.Manual} returns this
 */
proto.bot.Manual.prototype.clearEntrypoint = function() {
  return this.setEntrypoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.Manual.prototype.hasEntrypoint = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Trailing exitPoint = 2;
 * @return {?proto.bot.Trailing}
 */
proto.bot.Manual.prototype.getExitpoint = function() {
  return /** @type{?proto.bot.Trailing} */ (
    jspb.Message.getWrapperField(this, proto.bot.Trailing, 2));
};


/**
 * @param {?proto.bot.Trailing|undefined} value
 * @return {!proto.bot.Manual} returns this
*/
proto.bot.Manual.prototype.setExitpoint = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.Manual} returns this
 */
proto.bot.Manual.prototype.clearExitpoint = function() {
  return this.setExitpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.Manual.prototype.hasExitpoint = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Trigger lossCutPoint = 3;
 * @return {?proto.bot.Trigger}
 */
proto.bot.Manual.prototype.getLosscutpoint = function() {
  return /** @type{?proto.bot.Trigger} */ (
    jspb.Message.getWrapperField(this, proto.bot.Trigger, 3));
};


/**
 * @param {?proto.bot.Trigger|undefined} value
 * @return {!proto.bot.Manual} returns this
*/
proto.bot.Manual.prototype.setLosscutpoint = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.Manual} returns this
 */
proto.bot.Manual.prototype.clearLosscutpoint = function() {
  return this.setLosscutpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.Manual.prototype.hasLosscutpoint = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.bot.TriggerType.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.bot.TriggerType.TypeCase = {
  TYPE_NOT_SET: 0,
  MANUAL: 1
};

/**
 * @return {proto.bot.TriggerType.TypeCase}
 */
proto.bot.TriggerType.prototype.getTypeCase = function() {
  return /** @type {proto.bot.TriggerType.TypeCase} */(jspb.Message.computeOneofCase(this, proto.bot.TriggerType.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bot.TriggerType.prototype.toObject = function(opt_includeInstance) {
  return proto.bot.TriggerType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bot.TriggerType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.TriggerType.toObject = function(includeInstance, msg) {
  var f, obj = {
    manual: (f = msg.getManual()) && proto.bot.Manual.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bot.TriggerType}
 */
proto.bot.TriggerType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bot.TriggerType;
  return proto.bot.TriggerType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bot.TriggerType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bot.TriggerType}
 */
proto.bot.TriggerType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bot.Manual;
      reader.readMessage(value,proto.bot.Manual.deserializeBinaryFromReader);
      msg.setManual(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bot.TriggerType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bot.TriggerType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bot.TriggerType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.TriggerType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getManual();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.bot.Manual.serializeBinaryToWriter
    );
  }
};


/**
 * optional Manual manual = 1;
 * @return {?proto.bot.Manual}
 */
proto.bot.TriggerType.prototype.getManual = function() {
  return /** @type{?proto.bot.Manual} */ (
    jspb.Message.getWrapperField(this, proto.bot.Manual, 1));
};


/**
 * @param {?proto.bot.Manual|undefined} value
 * @return {!proto.bot.TriggerType} returns this
*/
proto.bot.TriggerType.prototype.setManual = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.bot.TriggerType.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.TriggerType} returns this
 */
proto.bot.TriggerType.prototype.clearManual = function() {
  return this.setManual(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.TriggerType.prototype.hasManual = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bot.Bot.prototype.toObject = function(opt_includeInstance) {
  return proto.bot.Bot.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bot.Bot} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.Bot.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    basecurrency: jspb.Message.getFieldWithDefault(msg, 3, ""),
    createdat: (f = msg.getCreatedat()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    tradingamount: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    currentvaluation: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    realizedprofit: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    autoReinvestment: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    trigger: (f = msg.getTrigger()) && proto.bot.TriggerType.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bot.Bot}
 */
proto.bot.Bot.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bot.Bot;
  return proto.bot.Bot.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bot.Bot} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bot.Bot}
 */
proto.bot.Bot.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBasecurrency(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedat(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTradingamount(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCurrentvaluation(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setRealizedprofit(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutoReinvestment(value);
      break;
    case 9:
      var value = new proto.bot.TriggerType;
      reader.readMessage(value,proto.bot.TriggerType.deserializeBinaryFromReader);
      msg.setTrigger(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bot.Bot.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bot.Bot.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bot.Bot} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.Bot.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBasecurrency();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCreatedat();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTradingamount();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getCurrentvaluation();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getRealizedprofit();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getAutoReinvestment();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getTrigger();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.bot.TriggerType.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.bot.Bot.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bot.Bot} returns this
 */
proto.bot.Bot.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.bot.Bot.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bot.Bot} returns this
 */
proto.bot.Bot.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string baseCurrency = 3;
 * @return {string}
 */
proto.bot.Bot.prototype.getBasecurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.bot.Bot} returns this
 */
proto.bot.Bot.prototype.setBasecurrency = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp createdAt = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.bot.Bot.prototype.getCreatedat = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.bot.Bot} returns this
*/
proto.bot.Bot.prototype.setCreatedat = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.Bot} returns this
 */
proto.bot.Bot.prototype.clearCreatedat = function() {
  return this.setCreatedat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.Bot.prototype.hasCreatedat = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional double tradingAmount = 5;
 * @return {number}
 */
proto.bot.Bot.prototype.getTradingamount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.bot.Bot} returns this
 */
proto.bot.Bot.prototype.setTradingamount = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double currentValuation = 6;
 * @return {number}
 */
proto.bot.Bot.prototype.getCurrentvaluation = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.bot.Bot} returns this
 */
proto.bot.Bot.prototype.setCurrentvaluation = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional double realizedProfit = 7;
 * @return {number}
 */
proto.bot.Bot.prototype.getRealizedprofit = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.bot.Bot} returns this
 */
proto.bot.Bot.prototype.setRealizedprofit = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional bool auto_reinvestment = 8;
 * @return {boolean}
 */
proto.bot.Bot.prototype.getAutoReinvestment = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.bot.Bot} returns this
 */
proto.bot.Bot.prototype.setAutoReinvestment = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional TriggerType trigger = 9;
 * @return {?proto.bot.TriggerType}
 */
proto.bot.Bot.prototype.getTrigger = function() {
  return /** @type{?proto.bot.TriggerType} */ (
    jspb.Message.getWrapperField(this, proto.bot.TriggerType, 9));
};


/**
 * @param {?proto.bot.TriggerType|undefined} value
 * @return {!proto.bot.Bot} returns this
*/
proto.bot.Bot.prototype.setTrigger = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bot.Bot} returns this
 */
proto.bot.Bot.prototype.clearTrigger = function() {
  return this.setTrigger(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bot.Bot.prototype.hasTrigger = function() {
  return jspb.Message.getField(this, 9) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bot.Position.prototype.toObject = function(opt_includeInstance) {
  return proto.bot.Position.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bot.Position} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.Position.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    botid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    symbol: jspb.Message.getFieldWithDefault(msg, 3, ""),
    status: jspb.Message.getFieldWithDefault(msg, 4, 0),
    tradingamount: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    valuation: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bot.Position}
 */
proto.bot.Position.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bot.Position;
  return proto.bot.Position.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bot.Position} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bot.Position}
 */
proto.bot.Position.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbol(value);
      break;
    case 4:
      var value = /** @type {!proto.bot.PositionStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTradingamount(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValuation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bot.Position.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bot.Position.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bot.Position} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bot.Position.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBotid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getTradingamount();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getValuation();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.bot.Position.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bot.Position} returns this
 */
proto.bot.Position.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string botId = 2;
 * @return {string}
 */
proto.bot.Position.prototype.getBotid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bot.Position} returns this
 */
proto.bot.Position.prototype.setBotid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string symbol = 3;
 * @return {string}
 */
proto.bot.Position.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.bot.Position} returns this
 */
proto.bot.Position.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional PositionStatus status = 4;
 * @return {!proto.bot.PositionStatus}
 */
proto.bot.Position.prototype.getStatus = function() {
  return /** @type {!proto.bot.PositionStatus} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.bot.PositionStatus} value
 * @return {!proto.bot.Position} returns this
 */
proto.bot.Position.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional double tradingAmount = 5;
 * @return {number}
 */
proto.bot.Position.prototype.getTradingamount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.bot.Position} returns this
 */
proto.bot.Position.prototype.setTradingamount = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double valuation = 6;
 * @return {number}
 */
proto.bot.Position.prototype.getValuation = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.bot.Position} returns this
 */
proto.bot.Position.prototype.setValuation = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * @enum {number}
 */
proto.bot.CompareOp = {
  EQ: 0,
  GT: 1,
  GTE: 2,
  LT: 3,
  LTE: 4
};

/**
 * @enum {number}
 */
proto.bot.PositionStatus = {
  CLOSED: 0,
  OPENED: 1
};

goog.object.extend(exports, proto.bot);
