name: "Build Backend"
on:
  push
env:
  SCCACHE_VER: v0.5.4
  RUSTC_WRAPPER: /usr/local/bin/sccache
jobs:
  build-libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.cache/sccache
            backend/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('backend/Cargo.lock') }}
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            musl-tools jq curl lld clang cmake protobuf-compiler \
            libprotobuf-dev
      - name: Setup Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Setup Rustfmt
        run: rustup component add rustfmt
      - name: Target to x86_64-unknown-linux-musl
        run: rustup target add x86_64-unknown-linux-musl
      - name: "Install sccache"
        run: |
          TARGET="sccache-${{env.SCCACHE_VER}}-x86_64-unknown-linux-musl"
          SCCACHE_ARCHIVE="${TARGET}.tar.gz"
          SCCACHE_URL='https://github.com/mozilla/sccache/releases/download/'
          SCCACHE_URL="${SCCACHE_URL}${{env.SCCACHE_VER}}/${SCCACHE_ARCHIVE}"
          curl -fLC - ${SCCACHE_URL} -o ${SCCACHE_ARCHIVE}
          tar xzf ${SCCACHE_ARCHIVE}
          mv "${TARGET}/sccache" ${{env.RUSTC_WRAPPER}}
          rm -rf ${SCCACHE_ARCHIVE} ${TARGET}
          chmod u+x ${{env.RUSTC_WRAPPER}}
      - name: "Extract musl dependencies"
        run: |
          mkdir ../deps
          tar xJvf openssl.txz -C ../deps
          tar xJvf gmp.txz -C ../deps
          tar xJvf mpfr.txz -C ../deps
          tar xJvf mpc.txz -C ../deps
        working-directory: ./.circleci
      - name: "Build the package"
        run: |
          cargo build -r \
            --target x86_64-unknown-linux-musl \
            --lib
          cargo build -r \
            --target x86_64-unknown-linux-musl \
            -p clients \
            -p executors \
            -p history \
            -p notification \
            -p observers \
            -p symbols
          # -p sign
        working-directory: ./backend
      - name: "Compress the built files"
        run: tar --zstd -cvf target.tzst target
        working-directory: ./backend
      - name: "Upload the package"
        uses: actions/upload-artifact@v2
        with:
          name: target.tzst
          path: backend/target.tzst
  build-bot_service:
    needs: build-libs
    uses: hiroaki-yamamoto/midas/.github/workflows/backend-bin-template.yml@feat/github-parallel-build
    with:
      pkgid: bot_service
      SCCACHE_VER: ${{ env.SCCACHE_VER }}
  build-historical_service:
    needs: build-libs
    uses: hiroaki-yamamoto/midas/.github/workflows/backend-bin-template.yml@feat/github-parallel-build
    with:
      pkgid: historical_service
      SCCACHE_VER: ${{ env.SCCACHE_VER }}
  build-keychain_service:
    needs: build-libs
    uses: hiroaki-yamamoto/midas/.github/workflows/backend-bin-template.yml@feat/github-parallel-build
    with:
      pkgid: keychain_service
      SCCACHE_VER: ${{ env.SCCACHE_VER }}
  build-symbol_service:
    needs: build-libs
    uses: hiroaki-yamamoto/midas/.github/workflows/backend-bin-template.yml@feat/github-parallel-build
    with:
      pkgid: symbol_service
      SCCACHE_VER: ${{ env.SCCACHE_VER }}
  build-token_service:
    needs: build-libs
    uses: hiroaki-yamamoto/midas/.github/workflows/backend-bin-template.yml@feat/github-parallel-build
    with:
      pkgid: token_service
      SCCACHE_VER: ${{ env.SCCACHE_VER }}
  build-trade_observer_service:
    needs: build-libs
    uses: hiroaki-yamamoto/midas/.github/workflows/backend-bin-template.yml@feat/github-parallel-build
    with:
      pkgid: trade_observer_service
      SCCACHE_VER: ${{ env.SCCACHE_VER }}
  # TODO: Transpiler Service
  build-historical_date_split_worker:
    needs: build-libs
    uses: hiroaki-yamamoto/midas/.github/workflows/backend-bin-template.yml@feat/github-parallel-build
    with:
      pkgid: historical_date_split_worker
      SCCACHE_VER: ${{ env.SCCACHE_VER }}
  build-historical_fetch_worker:
    needs: build-libs
    uses: hiroaki-yamamoto/midas/.github/workflows/backend-bin-template.yml@feat/github-parallel-build
    with:
      pkgid: historical_fetch_worker
      SCCACHE_VER: ${{ env.SCCACHE_VER }}
  build-notify_worker:
    needs: build-libs
    uses: hiroaki-yamamoto/midas/.github/workflows/backend-bin-template.yml@feat/github-parallel-build
    with:
      pkgid: notify_worker
      SCCACHE_VER: ${{ env.SCCACHE_VER }}
  build-trade_observer_worker:
    needs: build-libs
    uses: hiroaki-yamamoto/midas/.github/workflows/backend-bin-template.yml@feat/github-parallel-build
    with:
      pkgid: trade_observer_worker
      SCCACHE_VER: ${{ env.SCCACHE_VER }}
  build-trade_observer_control_worker:
    needs: build-libs
    uses: hiroaki-yamamoto/midas/.github/workflows/backend-bin-template.yml@feat/github-parallel-build
    with:
      pkgid: trade_observer_control_worker
      SCCACHE_VER: ${{ env.SCCACHE_VER }}
